Docker

diff --git a/frontend/docker/production/app/Dockerfile b/frontend/docker/production/app/Dockerfile
--- a/frontend/docker/production/app/Dockerfile
+++ b/frontend/docker/production/app/Dockerfile
@@ -1,38 +1,71 @@
-FROM node:22.11.0-alpine AS base
+FROM node:22-alpine AS base
 
-# setup docker image to install all node packages
-FROM base AS dependencies
+# 1. Install dependencies only when needed
+FROM base AS deps
+# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
+# RUN apk add --no-cache libc6-compat
 
 WORKDIR /app
 
-COPY package.json package-lock* ./
+# Install dependencies based on the preferred package manager
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
-RUN npm install
-
-
-# setup docker image for next.js build
-FROM base AS build
+# 2. Rebuild the source code only when needed
+FROM base AS builder
 WORKDIR /app
-COPY --from=dependencies /app/node_modules ./node_modules
+COPY --from=deps /app/node_modules ./node_modules
+# COPY --from=deps /root/.npm /root/.npm
 COPY . .
 
-ENV NEXT_TELEMETRY_DISABLED=1
+# Instalar o pnpm globalmente
+# RUN \
+#   npm install -g pnpm
+  # npm install @tailwindcss/oxide-linux-x64-musl \
+  # npm install lightningcss-linux-x64-gnu
 
+# This will do the trick, use the corresponding env file for each environment.
+#COPY .env.local .env
 RUN npm run build
 
-# setup docker image to hold build, static and run the app
+# 3. Production image, copy all the files and run next
 FROM base AS runner
 WORKDIR /app
 
-ENV NODE_ENV=production \
-    NEXT_TELEMETRY_DISABLED=1 \
-    HOSTNAME="0.0.0.0"
+ENV NEXT_SHARP_PATH=/tmp/node_modules/sharp
+ENV ENVIRONMENT production
+ENV NEXTAUTH_URL ${NEXTAUTH_URL}
+ENV NEXT_PUBLIC_API_URL ${NEXT_PUBLIC_API_URL}
 
-COPY --from=build /app/public ./public
+RUN addgroup -g 1001 -S nodejs
+RUN adduser -S nextjs -u 1001
 
-RUN mkdir .next
+COPY --from=builder /app/public ./public
 
-COPY --from=build /app/.next/standalone ./
-COPY --from=build /app/.next/static ./.next/static
+# Automatically leverage output traces to reduce image size
+# https://nextjs.org/docs/advanced-features/output-file-tracing
+COPY --from=builder /app/public ./public
+COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
+COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/standalone/.next/
+
+# COPY --from=builder --chown=nextjs:nodejs /app/.next ./.next
+# COPY --from=builder /app/node_modules ./node_modules
+# COPY --from=builder /app/package.json ./package.json
+
+
+USER nextjs
+
+EXPOSE 3000
+
+ENV PORT 3000
+
+ENV HOSTNAME "0.0.0.0"
+
+ENV PATH /app/node_modules/.bin:$PATH
 
 CMD ["node", "server.js"]
